repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
        files: .pre-commit-config.yaml
    -   id: end-of-file-fixer
        exclude: \.txt$
    -   id: trailing-whitespace
        exclude: \.txt$
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        files: ^(scripts/|src/|tests/)
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: ^(scripts/|src/|tests/)
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.289
    hooks:
    -   id: ruff
        files: ^(scripts/|src/|tests/)
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        files: ^(scripts/|src/|tests/)
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    -   id: gitlint
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest -n auto
        language: system
        types: [python]
        pass_filenames: false
