# Configuration for the Low-Volatility Defensive Strategy Example
#
# This file defines a custom universe tailored for the low-volatility
# defensive strategy example. It demonstrates how to configure a
# preselection step to favor low-volatility assets and a tight
# membership policy to minimize turnover.
#
# Example usage with `run_backtest.py`:
# python scripts/run_backtest.py equal_weight \
#   --universe-file config/lowvol_strategy_config.yaml \
#   --universe-name lowvol_defensive \
#   --start-date 2010-01-01 \
#   --end-date 2023-12-31 \
#   --rebalance-frequency quarterly

universes:
  lowvol_defensive:
    description: "Low-volatility strategy selecting top 20 assets from a universe of 500, with a tight membership policy."

    # For this example, we'll use a subset of the 1000-asset universe
    # to simulate a more focused 500-asset universe.
    assets: &long_history_500_assets [
        "A", "AA", "AAL", "AAP", "AAPL", "ABBV", "ABC", "ABT", "ACGL", "ACN",
        "ADBE", "ADI", "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG",
        "AIZ", "AJG", "AKAM", "ALB", "ALGN", "ALK", "ALL", "ALLE", "AMAT", "AMCR",
        "AMD", "AME", "AMGN", "AMP", "AMT", "AMZN", "ANET", "ANSS", "AON", "AOS",
        "APA", "APD", "APH", "APTV", "ARE", "ATO", "AVB", "AVY", "AWK", "AXP",
        "AZO", "BA", "BAC", "BALL", "BAX", "BBWI", "BBY", "BDX", "BEN", "BF-B",
        "BG", "BIIB", "BIO", "BK", "BKNG", "BKR", "BLK", "BMY", "BR", "BRO",
        "BSX", "BWA", "BXP", "C", "CAG", "CAH", "CARR", "CAT", "CB", "CBOE",
        "CBRE", "CCI", "CCL", "CDAY", "CDNS", "CDW", "CE", "CEG", "CF", "CFG",
        "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", "CMA", "CMCSA", "CME",
        "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COO", "COP", "COST", "CPB",
        "CPRT", "CPT", "CRL", "CRM", "CSCO", "CSGP", "CSX", "CTAS", "CTLT", "CTRA",
        "CTSH", "CVS", "CVX", "CZR", "D", "DAL", "DD", "DE", "DFS", "DG",
        "DGX", "DHI", "DHR", "DIS", "DISH", "DLR", "DLTR", "DOV", "DOW", "DPZ",
        "DRI", "DTE", "DUK", "DVA", "DVN", "DXC", "DXCM", "EA", "EBAY", "ECL",
        "ED", "EFX", "EIX", "EL", "ELV", "EMN", "EMR", "ENPH", "EOG", "EPAM",
        "EQIX", "EQR", "EQT", "ERJ", "ES", "ESS", "ETN", "ETR", "ETSY", "EVRG",
        "EW", "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS",
        "FDX", "FE", "FFIV", "FICO", "FIS", "FISV", "FITB", "FLT", "FMC", "FOX",
        "FOXA", "FRT", "FSLR", "FTNT", "FTV", "GD", "GE", "GEHC", "GEN", "GILD",
        "GIS", "GL", "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN",
        "GS", "GWW", "HAL", "HAS", "HBAN", "HCA", "HD", "HES", "HIG", "HII",
        "HLT", "HOLX", "HON", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUM",
        "HWM", "IBM", "ICE", "IDXX", "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU",
        "INVH", "IP", "IPG", "IQV", "IRM", "ISRG", "IT", "ITW", "IVZ", "J",
        "JBL", "JCI", "JEF", "JNJ", "JNPR", "JPM", "K", "KDP", "KEY", "KEYS",
        "KHC", "KIM", "KLAC", "KMB", "KMI", "KMX", "KO", "KR", "KVUE", "L",
        "LDOS", "LEN", "LH", "LHX", "LIN", "LKQ", "LLY", "LMT", "LNC", "LNT",
        "LOW", "LULU", "LUV", "LVS", "LW", "LYB", "LYV", "MA", "MAA", "MAR",
        "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", "META", "MGM",
        "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM", "MNST", "MO", "MOH", "MOS",
        "MPC", "MPWR", "MRK", "MRNA", "MRO", "MS", "MSCI", "MSFT", "MSI", "MTB",
        "MTCH", "MTD", "MU", "NCLH", "NDAQ", "NEE", "NEM", "NFLX", "NI", "NKE",
        "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWS",
        "NWSA", "NXPI", "O", "ODFL", "OGN", "OKE", "OMC", "ON", "ORCL", "ORLY",
        "OTIS", "OXY", "PANW", "PARA", "PAYC", "PAYX", "PCAR", "PCG", "PEAK", "PEG",
        "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PM",
        "PNC", "PNR", "PNW", "PODD", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX",
        "PTC", "PWR", "PXD", "PYPL", "QCOM", "QRVO", "RCL", "REG", "REGN", "RF",
        "RHI", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX",
        "SBAC", "SBUX", "SCHW", "SJM", "SLB", "SNA", "SNPS", "SO", "SPG", "SPGI",
        "SRE", "STE", "STLD", "STT", "STX", "STZ", "SWK", "SWKS", "SYF", "SYK",
        "SYY", "T", "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TFX",
        "TGT", "TJX", "TMO", "TMUS", "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO",
        "TSLA", "TSN", "TT", "TTWO", "TXN", "TXT", "UAL", "UDR", "UHS", "ULTA"
    ]

    # Point-in-Time (PIT) Eligibility Configuration
    pit_eligibility:
      enabled: true
      min_history_days: 252

    # Preselection Configuration (Low-Volatility Factor)
    preselection:
      method: "low_vol"
      top_k: 20             # Select the top 20 assets with the lowest volatility
      lookback: 252         # Calculate volatility over the past 12 months
      min_periods: 126      # Require at least 6 months of data for calculation

    # Membership Policy (Tight Turnover Control)
    membership_policy:
      enabled: true
      min_holding_periods: 4  # Hold an asset for at least 4 quarters (1 year)
      max_turnover: 0.20      # Max 20% turnover per rebalance
      max_new_assets: 4       # Add at most 4 new assets per rebalance (20% of 20)
      max_removed_assets: 4   # Remove at most 4 assets per rebalance
