universes:
  long_history_30_integrated:
    description: Top-30 universe with PIT, preselection, and membership policy enabled
    assets:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - META
    - TSLA
    - NVDA
    - JPM
    - JNJ
    - V
    - PG
    - UNH
    - HD
    - MA
    - DIS
    - ADBE
    - NFLX
    - PYPL
    - INTC
    - CSCO
    - PEP
    - COST
    - CMCSA
    - AVGO
    - QCOM
    - TXN
    - AMGN
    - SBUX
    - INTU
    - AMD
    - HON
    - UNP
    - BA
    - CAT
    - MMM
    - GE
    - IBM
    - T
    - VZ
    - WMT
    - MCD
    - KO
    - XOM
    - CVX
    - LMT
    - RTX
    - BMY
    - MRK
    - GILD
    - ABT
    pit_eligibility:
      enabled: true
      min_history_days: 252
      min_price_rows: 252
    preselection:
      method: "momentum"
      top_k: 30
      lookback: 252
      skip: 1
      min_periods: 60
    membership_policy:
      enabled: true
      buffer_rank: 35
      min_holding_periods: 3
      max_turnover: 0.30
      max_new_assets: 5
      max_removed_assets: 5

  long_history_100:
    description: 100-asset universe with >=20y history across NYSE/Nasdaq/LSE
    assets:
    - AAL
    - BHP
    - CCL
    - CNA
    - CPG
    - III
    - IMB
    - SSE
    - AZN
    - OMU
    - SVT
    - BATS
    - LAND
    - DGE
    - LGEN
    - MKS
    - TSCO
    - ABF
    - VOD
    - NXT
    - AAPL
    - DLTR
    - GNTX
    - MNST
    - SNPS
    - ADBE
    - ADI
    - ADP
    - ADSK
    - AEP
    - AMAT
    - AMD
    - AMGN
    - APA
    - CMCSA
    - COST
    - EXC
    - GT
    - HAS
    - HON
    - INTC
    - KMB
    - MAT
    - MSFT
    - MU
    - NWL
    - PCAR
    - PEP
    - ROST
    - SLM
    - TER
    - TROW
    - TXN
    - WEN
    - XRX
    - AEM
    - AU
    - B
    - DAL
    - DLX
    - LPX
    - MSA
    - T
    - WEC
    - WOR
    - AA
    - AXP
    - BA
    - BMY
    - CAT
    - DD
    - DIS
    - DTE
    - ED
    - EIX
    - F
    - GD
    - GE
    - HPQ
    - IBM
    - IP
    - JNJ
    - JPM
    - KO
    - KR
    - LMT
    - MCD
    - MMM
    - MO
    - MRK
    - PCG
    - PEG
    - PG
    - R
    - RTX
    - UIS
    - UNP
    - WMT
    - WY
    - XOM
  long_history_1000:
    description: 1000-asset universe with >=20y history across global markets (long
      gaps removed)
    assets:
    - DAL
    - DAL:US
    - LPX:US
    - LPX
    - T
    - T:US
    - AAPL:US
    - AAPL
    - AEM:US
    - AEM
    - WEC
    - WEC:US
    - CXT
    - B
    - ATRO
    - MNST
    - MNST:US
    - DLX
    - RR.
    - LLOY
    - SCHW
    - GNTX
    - GNTX:US
    - WOR
    - SSE
    - SNPS:US
    - SNPS
    - MSA
    - MSA:US
    - III
    - RAVE
    - EMG
    - DLTR
    - DLTR:US
    - IMB
    - CNA
    - BHP
    - IHG
    - AU
    - CPG
    - AAL
    - CCL
    - IBCP
    - RIO
    - WWD
    - MSI:US
    - SBRA
    - MSI
    - ODFL
    - WWD:US
    - ODFL:US
    - SBRA:US
    - XOMA
    - VLO
    - VHI
    - UFI
    - WTI
    - SCL
    - VNO
    - SCS
    - UL
    - ZTR
    - UMC
    - UNFI
    - URI
    - UVV
    - UHT
    - SONY
    - SR
    - UHS
    - UTI
    - VSH
    - EGY
    - VTR
    - SWX
    - VMI
    - SCCO
    - MTN
    - VALE
    - TSN
    - UGI
    - UDR
    - TWI
    - TKR
    - TDW
    - THO
    - TTI
    - TEX
    - TNC
    - SKT
    - TS
    - TPR
    - HQH
    - TDY
    - SGI
    - TFX
    - TDS
    - TOL
    - WPC
    - TTE
    - RGR
    - STC
    - TYL
    - SF
    - TKC
    - STM
    - SRI
    - TRN
    - TSM
    - SUI
    - SHO
    - SNX
    - TREX
    - TRV
    - TM
    - TTC
    - WGO
    - WNC
    - AGO:US
    - BHC:US
    - BNS:US
    - AXS:US
    - AVA:US
    - AVNT:US
    - AVB:US
    - ALV:US
    - ASGN:US
    - WAB
    - ABG:US
    - AJG:US
    - ARW:US
    - MT:US
    - ABR:US
    - AIT:US
    - AON:US
    - BDC:US
    - BIO:US
    - BKH:US
    - BXMT:US
    - CNI:US
    - CCJ:US
    - CPT:US
    - CADE:US
    - CACI:US
    - CBT:US
    - BG:US
    - BKE:US
    - BRO:US
    - BN:US
    - BYD:US
    - BXP:US
    - SAM:US
    - BWA:US
    - BLK:US
    - NLY:US
    - APH:US
    - AMN:US
    - CAR.UN
    - TGB
    - IMO
    - WWW
    - WOLF
    - SQM
    - WSM
    - WEX
    - WLK
    - EMD
    - WST
    - WCC
    - WELL
    - WMK
    - WSO
    - WM
    - APT
    - INO.UN
    - AME:US
    - AD
    - AMT:US
    - AWR:US
    - AEO:US
    - LNT:US
    - ALE:US
    - ARE:US
    - ALB:US
    - ALK:US
    - ADC:US
    - AGCO:US
    - AAP:US
    - ATGE:US
    - ACN:US
    - ABM:US
    - ANF:US
    - SON
    - SBR
    - SJM
    - LXP
    - MED
    - MATX
    - MTZ
    - MLM
    - MKL
    - HZO
    - M
    - VRE
    - MAC
    - MSM
    - MHO
    - MGM
    - MFA
    - MDU
    - L
    - LYG
    - RAMP
    - MD
    - MCY
    - MTH
    - TAP
    - NRG
    - NL
    - MUR
    - MLI
    - MOV
    - MOS
    - MS
    - MOH
    - MSB
    - MHK
    - MOD
    - MUFG
    - MTX
    - MAA
    - MTD
    - MEI
    - LAD
    - LEN
    - AOS
    - EL
    - INVX
    - INGR
    - ING
    - INFY
    - IFN
    - IEX
    - IDA
    - IBN
    - IRS
    - IDT
    - HUN
    - HOV
    - HRL
    - HMN
    - HMC
    - HIW
    - HXL
    - IIM
    - IRM
    - ITUB
    - KEP
    - LVS
    - LZB
    - LH
    - LHX
    - LTC
    - LCII
    - LPL
    - PHG
    - J
    - KEX
    - KIM
    - KRC
    - KFRC
    - KAI
    - JLL
    - JEF
    - NVR
    - NOV
    - NFG
    - NGG
    - ROG
    - RMD
    - RSG
    - RELX
    - RS
    - RGA
    - RRX
    - RWT
    - O
    - RYN
    - RJF
    - RRC
    - RL
    - RES
    - RLI
    - PWR
    - KWR
    - ROL
    - RHP
    - SLG
    - MATV
    - SNN
    - SKY
    - SSD
    - SLGN
    - SHG
    - SCI
    - SMG
    - BFS
    - SM
    - SSL
    - SAP
    - SJT
    - CRM
    - JOE
    - CSL:US
    - SPXC
    - PSA
    - PFS
    - PBH
    - NWN
    - ORI
    - OIS
    - OII
    - OI
    - NUS
    - NVO
    - NVS
    - NMR
    - OHI
    - NOK
    - NEE
    - NPKI
    - FLG
    - NNI
    - NNN
    - NHI
    - OLN
    - OLP
    - PII
    - PVH
    - PIPR
    - PHD
    - PBR
    - PBR.A
    - TLK
    - PBT
    - PAG
    - PKX
    - OKE
    - PHI
    - OXM
    - OVV
    - OSK
    - ORA
    - IX
    - ONTO
    - CNQ:US
    - FIX:US
    - KMX:US
    - HWC:US
    - COHR:US
    - CTSH:US
    - CGNX:US
    - CCOI:US
    - COKE:US
    - CME:US
    - CHDN:US
    - CAKE:US
    - CENX:US
    - CVCO:US
    - CWST:US
    - CDNS:US
    - BRKS:US
    - TECH:US
    - BCRX:US
    - BGC:US
    - OZK:US
    - COLB:US
    - COLM:US
    - COO:US
    - EXEL:US
    - HAIN:US
    - ROCK:US
    - FCEL:US
    - FELE:US
    - FOSL:US
    - FFIV:US
    - EXPO:US
    - EEFT:US
    - CPRT:US
    - EPR:US
    - ENTG:US
    - ESLT:US
    - EWBC:US
    - DIOD:US
    - CBRL:US
    - CSGP:US
    - BCPC:US
    - ACLS:US
    - AVT:US
    - URI:US
    - WSO:US
    - WM:US
    - WAB:US
    - VNO:US
    - VTR:US
    - VLO:US
    - UHS:US
    - UGI:US
    - WST:US
    - UDR:US
    - TSN:US
    - TREX:US
    - TRV:US
    - TD:US
    - THO:US
    - TEX:US
    - WELL:US
    - WTM:US
    - CAR:US
    - ALGN:US
    - ASRT:US
    - ASML:US
    - ARCC:US
    - ACGL:US
    - AMKR:US
    - ABCB:US
    - DOX:US
    - AKAM:US
    - WSM:US
    - AEIS:US
    - ACIW:US
    - EGHT:US
    - FLWS:US
    - WRB:US
    - WPC:US
    - WOLF:US
    - HALO:US
    - HELE:US
    - TFX:US
    - HOLX:US
    - STLD:US
    - STAA:US
    - SSB:US
    - SWKS:US
    - SKYW:US
    - SLAB:US
    - SMTC:US
    - STX:US
    - SBAC:US
    - SGMO:US
    - SAIA:US
    - RUSHA:US
    - RGLD:US
    - RGEN:US
    - REG:US
    - RMBS:US
    - QDEL:US
    - SHOO:US
    - SSYS:US
    - STRA:US
    - URBN:US
    - WYNN:US
    - WDC:US
    - WERN:US
    - WDFC:US
    - VSAT:US
    - VRNT:US
    - VCEL:US
    - OLED:US
    - TTWO:US
    - UTHR:US
    - UNFI:US
    - UBSI:US
    - UFPI:US
    - TRMB:US
    - TSCO:US
    - TTEK:US
    - PSEC:US
    - PRGS:US
    - POWI:US
    - JACK:US
    - LFUS:US
    - LECO:US
    - LSCC:US
    - KLIC:US
    - KTOS:US
    - JBLU:US
    - JBHT:US
    - JKHY:US
    - LKQ:US
    - ITRI:US
    - ISRG:US
    - IART:US
    - INCY:US
    - ILMN:US
    - ICUI:US
    - ICLR:US
    - LPSN:US
    - LTC:US
    - POOL:US
    - NTGR:US
    - PENN:US
    - PEGA:US
    - PAAS:US
    - OMCL:US
    - NVEC:US
    - NDSN:US
    - NBIX:US
    - NEOG:US
    - MKTX:US
    - MYGN:US
    - MPWR:US
    - MKSI:US
    - MVIS:US
    - MSTR:US
    - MMSI:US
    - MRCY:US
    - TU:US
    - TDY:US
    - CRS:US
    - JEF:US
    - GPN:US
    - GNW:US
    - IT:US
    - GME:US
    - FCN:US
    - FMC:US
    - FLS:US
    - FLO:US
    - FIS:US
    - FRT:US
    - FICO:US
    - FDS:US
    - EXR:US
    - ES:US
    - EVRG:US
    - EL:US
    - ESS:US
    - GGG:US
    - GTN:US
    - GBX:US
    - HST:US
    - IRM:US
    - IVZ:US
    - ITGR:US
    - INGR:US
    - IMO:US
    - IEX:US
    - HUN:US
    - HRL:US
    - GPI:US
    - HXL:US
    - HLF:US
    - HP:US
    - HEI:US
    - HE:US
    - HOG:US
    - GES:US
    - WTRG:US
    - EQT:US
    - ENS:US
    - CLH:US
    - CMC:US
    - HLX
    - CDE:US
    - CNX:US
    - CNO:US
    - CNA:US
    - CLF:US
    - CHD:US
    - CRK:US
    - CHH:US
    - LNG:US
    - CHE:US
    - CRL:US
    - CNC:US
    - CE:US
    - CBRE:US
    - CMP:US
    - STZ:US
    - ENR:US
    - DLB:US
    - ENB:US
    - EME:US
    - EGO:US
    - EW:US
    - EXP:US
    - DY:US
    - DHI:US
    - DLR:US
    - CTRA:US
    - DB:US
    - DECK:US
    - DVA:US
    - DAR:US
    - CW:US
    - CCK:US
    - CCI:US
    - J:US
    - SJM:US
    - SKT:US
    - JLL:US
    - RL:US
    - PWR:US
    - QGEN:US
    - PVH:US
    - PSA:US
    - PRG:US
    - PII:US
    - PRGO:US
    - PNR:US
    - PAG:US
    - PKG:US
    - OMI:US
    - ON:US
    - ORA:US
    - OKE:US
    - OHI:US
    - OLN:US
    - RRC:US
    - O:US
    - RS:US
    - SIG:US
    - SNX:US
    - SLF:US
    - STM:US
    - SON:US
    - AOS:US
    - SLG:US
    - SSD:US
    - SFL:US
    - RNR:US
    - CRM:US
    - RHP:US
    - RCL:US
    - ROP:US
    - ROL:US
    - RMD:US
    - RSG:US
    - ORI:US
    - OIS:US
    - OGE:US
    - LAD:US
    - MLM:US
    - MKL:US
    - MFC:US
    - MAN:US
    - MGA:US
    - MAC:US
    - L:US
    - LII:US
    - MDU:US
    - LEN:US
    - LCII:US
    - LVS:US
    - LHX:US
    - KFY:US
    - KEX:US
    - KIM:US
    - MTZ:US
    - MED:US
    - OI:US
    - MOV:US
    - NVR:US
    - NRG:US
    - NNN:US
    - NEE:US
    - NFG:US
    - MUR:US
    - MSM:US
    - MOS:US
    - MCY:US
    - MS:US
    - TAP:US
    - MOH:US
    - MHK:US
    - MAA:US
    - MGM:US
    - MTD:US
    - HP
    - VLT
    - HLIO
    - NEOG
    - NICE
    - NBIX
    - NTCT
    - NTGR
    - NTES
    - NFLX
    - NVEC
    - NWPX
    - MYGN
    - MPWR
    - MLKN
    - MSEX
    - MIDD
    - MSTR
    - NDSN
    - NWE
    - MMSI
    - OXSQ
    - PETS
    - PENN
    - PEGA
    - PZZA
    - PRAA
    - PDFS
    - OTTR
    - ORLY
    - OPCH
    - OSPN
    - FLWS
    - 'ON'
    - ZEUS
    - OMEX
    - MVIS
    - MRCY
    - PPC
    - JAKK
    - KTOS
    - KOPN
    - KRNY
    - KVHI
    - ZD
    - JBLU
    - JJSF
    - LKQ
    - ISRG
    - IPAR
    - IART
    - INSG
    - INO
    - IOSP
    - KLIC
    - LKFN
    - MERC
    - MANH
    - MFIN
    - MGRC
    - MATW
    - MTRX
    - MRTN
    - MKTX
    - MKSI
    - LSCC
    - MGPI
    - MGEE
    - LPSN
    - LFUS
    - LECO
    - LTBR
    - PLAB
    - PNFP
    - INOD
    - TTEK
    - TTEC
    - TRMK
    - TCOM
    - TRMB
    - TSCO
    - TCBI
    - TTWO
    - UBSI
    - TTMI
    - SYNA
    - STRA
    - STRL
    - STLD
    - STGW
    - UFPI
    - UTHR
    - SPOK
    - VICR
    - WRLD
    - WTFC
    - WDC
    - WERN
    - WDFC
    - VOD
    - VSAT
    - OLED
    - VCEL
    - VRNT
    - VECO
    - VLY
    - URBN
    - ULH
    - STAA
    - SOHU
    - PLXS
    - RMBS
    - RIGL
    - RELL
    - RBBN
    - RGP
    - RGEN
    - REG
    - RICK
    - RGLD
    - QUIK
    - PSEC
    - PRGS
    - POWL
    - PCH
    - POOL
    - ROP
    - SEIC
    - SWBI
    - SSP
    - SNBR
    - SWKS
    - SIRI
    - SBGI
    - SLAB
    - SMTC
    - LNW
    - HTO
    - SCHL
    - SVRA
    - SNY
    - SGMO
    - SAIA
    - SAFT
    - NSIT
    - IMKTA
    - ZBRA
    - AVT
    - OZK
    - TBBK
    - BANF
    - BCPC
    - AXON
    - ACLS
    - CAR
    - BELFB
    - AZN
    - AROW
    - ARCC
    - ARCB
    - MFIC
    - APOG
    - BBSI
    - BCRX
    - ANGO
    - CVBF
    - CLDX
    - CASY
    - CWST
    - CHY
    - CALM
    - CDNS
    - CSGS
    - TECH
    - CME
    - CECO
    - BRKR
    - AZTA
    - BKNG
    - BJRI
    - ANIK
    - ANDE
    - CNTY
    - ICLR
    - RDWR
    - AUDC
    - ESLT
    - STX
    - AVDL
    - WTW
    - DOX
    - SSYS
    - SSRM
    - OTEX
    - BLDP
    - GLNG
    - HELE
    - ACGL
    - CRNT
    - CWCO
    - AMKR
    - AGEN
    - CRMT
    - AMSC
    - LNT
    - ALGN
    - AKAM
    - AGYS
    - AEIS
    - BPOP
    - ADTN
    - ACIW
    - ACTG
    - AXTI
    - ANIP
    - AAON
    - CENX
    - CERS
    - INDB
    - FOSL
    - GOOD
    - GLAD
    - ROCK
    - FCEL
    - FTEK
    - FELE
    - FWRD
    - GIFI
    - FORM
    - FCFS
    - FRME
    - FBNC
    - FFIV
    - EZPW
    - GGAL
    - HCKT
    - EXPO
    - HURC
    - INCY
    - IMMR
    - ILMN
    - IDXX
    - ICUI
    - HURN
    - JBHT
    - HAIN
    - HUBG
    - HST
    - HOLX
    - JKHY
    - HLIT
    - HALO
    - EXTR
    - EXEL
    - CAKE
    - CBSH
    - CSGP
    - QDEL
    - CPRT
    - CMTL
    - CTBI
    - CVGI
    - COHU
    - CRESY
    - CTSH
    - CGNX
    - CCOI
    - COKE
    - CRUS
    - CHDN
    - CBRL
    - CCRN
    - EVRG
    - EGHT
    - EEFT
    - ERIE
    - ERIC
    - EQIX
    - ENTG
    - ECPG
    - EWBC
    - BOOM
    - DPZ
    - DHC
    - DIOD
    - DGII
    - DENN
    - DAKT
    - WYNN
    - SBAC
    - LNG
    - KOF
    - CYH
    - CMC
    - FIX
    - RNP
    - COHR
    - CNS
    - CDE
    - CLF
    - CRI
    - CLH
    - CHD
    - CPK
    - ASML
    - CHE
    - CRL
    - CNC
    - CIG
    - SID
    - ELP
    - CCU
    - DHI
    - CW
    - CFR
    - CTO
    - CCI
    - CRT
    - CUZ
    - CDP
    - CXW
