# Predefined universes used by the portfolio construction pipeline.
# Each universe pairs selection filters with classification and return
# preparation settings. See docs/universes.md for full guidance.

universes:
  core_global:
    description: "Global core sleeve of diversified ETFs"
    filter_criteria:
      # High quality data only (clean files with 3+ years of history)
      data_status: ["ok"]
      min_history_days: 756
      min_price_rows: 756
      markets: ["LSE", "GBR-LSE"]
      currencies: ["GBP"]
      categories:
        - "lse etfs/1"
        - "lse etfs/2"
    classification_requirements:
      # Retain broad asset coverage for diversified core exposure
      asset_class: ["equity", "commodity", "real_estate"]
      geography: ["united_kingdom", "north_america"]
    return_config:
      method: "simple"
      frequency: "monthly"
      handle_missing: "forward_fill"
      max_forward_fill_days: 5
      min_periods: 5
      align_method: "outer"
      min_coverage: 0.85
    constraints:
      min_assets: 30
      max_assets: 50

  satellite_factor:
    description: "Factor / satellite sleeve (growth, value, small-cap tilts)"
    filter_criteria:
      data_status: ["ok", "warning"]
      min_history_days: 600
      min_price_rows: 600
      markets: ["GBR-LSE", "LSE", "NSQ", "NYSE"]
      currencies: ["USD", "GBP"]
      categories:
        - "lse etfs/1"
        - "lse etfs/2"
        - "nasdaq stocks/2"
        - "nasdaq stocks/3"
        - "nyse stocks/1"
        - "nyse stocks/2"
      allowlist:
        - ASDV:LN
        - BATT:LN
        - BME
        - CTO
        - DGRA:LN
        - GGRP:LN
        - GGRW
        - GLDV:LN
        - IDP6:LN
        - IDVY:LN
        - IEDY:LN
        - R2US:LN
        - RWAY
        - SRG
        - TDIV:LN
        - UDVD:LN
        - USVL
        - VALU
        - VHYL:LN
        - WSML:LN
    classification_requirements:
      asset_class: ["equity"]
      sub_class: ["growth", "value", "small_cap", "dividend"]
    return_config:
      method: "log"
      frequency: "weekly"
      handle_missing: "interpolate"
      max_forward_fill_days: 10
      min_periods: 5
      align_method: "outer"
      min_coverage: 0.4
    constraints:
      min_assets: 20
      max_assets: 35
    preselection:
      # Optional: Pre-filter assets using momentum and low-volatility factors
      method: "combined"  # Options: momentum, low_vol, combined
      top_k: 25  # Select top 25 assets before portfolio optimization
      lookback: 252  # 1 year lookback for factor calculation
      skip: 1  # Skip most recent day (common in momentum strategies)
      momentum_weight: 0.5  # Weight for momentum factor (when using combined)
      low_vol_weight: 0.5  # Weight for low-volatility factor (when using combined)
      min_periods: 60  # Minimum data required for valid calculation
    membership_policy:
      # Optional: Control asset turnover and stability during rebalancing
      enabled: true  # Enable/disable membership policy
      buffer_rank: 35  # Keep existing holdings if ranked within top 35 (even if outside top_k)
      min_holding_periods: 3  # Hold assets for at least 3 rebalance periods
      max_turnover: 0.30  # Maximum 30% portfolio turnover per rebalance
      max_new_assets: 5  # Add at most 5 new assets per rebalance
      max_removed_assets: 5  # Remove at most 5 assets per rebalance

  defensive:
    description: "Defensive sleeve (income, precious metals, property)"
    filter_criteria:
      data_status: ["ok"]
      min_history_days: 756
      min_price_rows: 756
      markets: ["LSE", "GBR-LSE"]
      currencies: ["USD", "GBP"]
      categories:
        - "lse stocks"
        - "lse etfs/1"
        - "lse etfs/2"
    classification_requirements:
      sub_class: ["gold", "reit", "dividend"]
    return_config:
      method: "simple"
      frequency: "monthly"
      handle_missing: "drop"
      min_periods: 5
      align_method: "inner"
      min_coverage: 0.9
    constraints:
      min_assets: 10
      max_assets: 20

  equity_only:
    description: "Pure equity growth sleeve (US + UK large/mid cap)"
    pit_eligibility:
      # Optional: Enable point-in-time eligibility filtering to avoid lookahead bias
      enabled: true
      min_history_days: 252  # Require 1 year of history
      min_price_rows: 252  # Require 252 valid price observations
    filter_criteria:
      data_status: ["ok"]
      min_history_days: 756
      min_price_rows: 756
      markets: ["NSQ", "NYSE", "LSE", "GBR-LSE"]
      currencies: ["USD", "GBP"]
      categories:
        - "nasdaq stocks/1"
        - "nasdaq stocks/2"
        - "nyse stocks/1"
        - "nyse stocks/2"
        - "lse stocks"
      allowlist:
        - DAL
        - LPX
        - AAPL
        - AEM
        - CXT
        - B
        - ATRO
        - DLX
        - GNTX
        - AXGN
        - DLTR
        - AU
        - IBCP
        - BRC
        - BLK
        - BDN
        - EAT
        - BCO
        - BYD
        - BXP
        - BWA
        - BRO
        - BXMT
        - BKH
        - GPN
        - GBCI
        - GTY
        - GGB
        - BIO
        - BHP
        - BHE
        - BZH
        - BTI
        - CBRE
        - CBZ
        - CYH
        - CMC
        - FIX
        - COHR
        - CNS
        - CDE
        - GNW
        - IT
        - GME
        - BDC
        - GEO
        - GATX
        - FUL
        - FMX
        - FLS
        - FLO
        - CRS
        - CUK
        - KMX
        - CSL
        - CPT
        - CWT
        - AJG
        - AXL
        - AMX
    classification_requirements:
      asset_class: ["equity"]
      geography: ["north_america", "united_kingdom"]
    return_config:
      method: "simple"
      frequency: "monthly"
      handle_missing: "forward_fill"
      max_forward_fill_days: 5
      min_periods: 5
      align_method: "outer"
      min_coverage: 0.7
    constraints:
      min_assets: 40
      max_assets: 60

  # Example universe with technical indicators (stub/no-op implementation)
  equity_with_indicators:
    description: "Equity sleeve with technical indicator filtering (no-op stub)"
    filter_criteria:
      data_status: ["ok"]
      min_history_days: 756
      min_price_rows: 756
      markets: ["LSE", "GBR-LSE"]
      currencies: ["GBP"]
      categories:
        - "lse etfs/1"
        - "lse etfs/2"
    classification_requirements:
      asset_class: ["equity"]
    return_config:
      method: "simple"
      frequency: "monthly"
      handle_missing: "forward_fill"
      max_forward_fill_days: 5
      min_periods: 5
      align_method: "outer"
      min_coverage: 0.85
    constraints:
      min_assets: 20
      max_assets: 40
    # Technical indicators configuration (currently using no-op provider)
    # This prepares for future integration with ta-lib, ta, or similar libraries
    technical_indicators:
      enabled: true
      provider: "noop"  # Options: 'noop', 'talib', 'ta' (only 'noop' currently supported)
      params:
        window: 20        # Example parameter for future indicator implementations
        threshold: 0.5    # Example threshold for signal filtering
