universes:
  long_history_100:
    description: 100-asset universe with >=20y history across NYSE/Nasdaq/LSE
    assets:
    - AAL
    - BHP
    - CCL
    - CNA
    - CPG
    - III
    - IMB
    - SSE
    - AZN
    - OMU
    - SVT
    - BATS
    - LAND
    - DGE
    - LGEN
    - MKS
    - TSCO
    - ABF
    - VOD
    - NXT
    - AAPL
    - DLTR
    - GNTX
    - MNST
    - SNPS
    - ADBE
    - ADI
    - ADP
    - ADSK
    - AEP
    - AMAT
    - AMD
    - AMGN
    - APA
    - CMCSA
    - COST
    - EXC
    - GT
    - HAS
    - HON
    - INTC
    - KMB
    - MAT
    - MSFT
    - MU
    - NWL
    - PCAR
    - PEP
    - ROST
    - SLM
    - TER
    - TROW
    - TXN
    - WEN
    - XRX
    - AEM
    - AU
    - B
    - DAL
    - DLX
    - LPX
    - MSA
    - T
    - WEC
    - WOR
    - AA
    - AXP
    - BA
    - BMY
    - CAT
    - DD
    - DIS
    - DTE
    - ED
    - EIX
    - F
    - GD
    - GE
    - HPQ
    - IBM
    - IP
    - JNJ
    - JPM
    - KO
    - KR
    - LMT
    - MCD
    - MMM
    - MO
    - MRK
    - PCG
    - PEG
    - PG
    - R
    - RTX
    - UIS
    - UNP
    - WMT
    - WY
    - XOM
