name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install --timeout=120 --retries 3 -r requirements.txt
          python -m pip install --timeout=120 --retries 3 -r requirements-dev.txt
          python -m pip install -e .

      - name: Verify critical dependencies
        run: |
          python -c "import pandas; import numpy; import yaml; import scipy; import cvxpy; print('Core dependencies OK')"
          python -c "import empyrical; print('empyrical-reloaded OK')"
          python -c "import pypfopt; print('PyPortfolioOpt OK')"
          python -c "import riskparityportfolio; print('riskparityportfolio OK')"
          python -c "import portfolio_management; print('portfolio_management package OK')"

      - name: Run pytest suite
        run: |
          pytest -m "not integration"
